### ISSUE TITLE
"lastIndexOf" should be "indexOf"

### ISSUE THREAD

**Issue by connorjclark** [JonUK/eleventy-blog#4]
```const endPosition = content.lastIndexOf(separators.end);``` should instead use "indexOf". Otherwise it grabs way too much for the `<p>` fallback.

thanks for the tutorial, it's been very helpful!

**Comment by JonUK** [comment]
It's a fair point. The original idea was that if there was no except start / end comments then the whole article would be displayed on the homepage but this could be too much with large articles. I agree that the first paragraph makes more sense.

Glad to hear you liked the tutorial. :)

**Comment by JonUK** [comment]
Code change commited: https://github.com/JonUK/eleventy-blog/commit/06ce708b5720c315755c96aea4135036c80a4f07
