### ISSUE TITLE
dateReadable should use utc

### ISSUE THREAD

**Issue by connorjclark** [JonUK/eleventy-blog#5]
Hi, me again :)

The number of the month was off by one, until I made this change:

```
eleventyConfig.addFilter('dateReadable', date => {
    return moment(date).utc().format('LL'); // E.g. May 31, 2019
  });
```

**Comment by JonUK** [comment]
Hello again :)

Out of interest, what format was the date in the front matter when you saw this issue?

The return of `dateReadable` when using an ISO format `YYYY-MM-DD` date is a string in UTC offset, as denoted by the suffix "Z", so wouldn't expect to have to explicitly call UTC?

I've added some unit tests on the filter so be good to see if these pass for you.
https://github.com/JonUK/eleventy-blog/blob/master/tests/.eleventy.test.js

**Comment by connorjclark** [comment]
I think it may be because you are in the UK but I am in the US (PT).

I see the same thing even with `Date` (removing moment from the equation`.

![image](https://user-images.githubusercontent.com/4071474/83458689-c3899c00-a417-11ea-9701-c6df450b4a4c.png)

**Comment by JonUK** [comment]
I see. Good spot. Have made that change to prevent timezone issues.
ed508034e8e6b6143e1ec9a0853b15623fe36ae8
